### ISSUE TITLE
speed up snakes with uncompressed hal?

### ISSUE THREAD

**Issue by joelarmstrong** [BD2KGenomics/mouseStrains#32]
Even

**Comment by joelarmstrong** [comment]
Seems like we might get a roughly 2x speed improvement, according to a small test example, although the speed doesn't come from removing the compression so much as being able to directly index into a contiguous array.

Testing the full mouse dataset now.

Compressed:
```
(python) kolossus  .../submodules/hal/chain/test  > ./blockVizBenchmark.py --reps 10 ~/progressiveCactus/mammals1/original.hal simHuman_chr6 simHuman.chr6 500000 simCow_chr6 --seed 340340          
Bin, nElem, totTime, minTime, maxTime, avgTime
2000, 1, 0.146405, 0.146405, 0.146405, 0.146405
10000, 1, 0.173400, 0.173400, 0.173400, 0.173400
93000, 1, 1.025122, 1.025122, 1.025122, 1.025122
165000, 1, 1.757006, 1.757006, 1.757006, 1.757006
231000, 1, 2.171318, 2.171318, 2.171318, 2.171318
384000, 1, 4.196661, 4.196661, 4.196661, 4.196661
411000, 1, 4.529850, 4.529850, 4.529850, 4.529850
422000, 1, 4.609316, 4.609316, 4.609316, 4.609316
442000, 1, 4.738765, 4.738765, 4.738765, 4.738765
458000, 1, 4.916651, 4.916651, 4.916651, 4.916651
```

Uncompressed:
```
(python) kolossus  .../submodules/hal/chain/test  > ./blockVizBenchmark.py --reps 10 ~/progressiveCactus/mammals1/original_uncompressed.hal simHuman_chr6 simHuman.chr6 500000 simCow_chr6 --seed 340
340
Bin, nElem, totTime, minTime, maxTime, avgTime
2000, 1, 0.142525, 0.142525, 0.142525, 0.142525
10000, 1, 0.179855, 0.179855, 0.179855, 0.179855
93000, 1, 1.021542, 1.021542, 1.021542, 1.021542
165000, 1, 1.709817, 1.709817, 1.709817, 1.709817
231000, 1, 2.191777, 2.191777, 2.191777, 2.191777
384000, 1, 4.246918, 4.246918, 4.246918, 4.246918
411000, 1, 4.478205, 4.478205, 4.478205, 4.478205
422000, 1, 4.785822, 4.785822, 4.785822, 4.785822
442000, 1, 4.667155, 4.667155, 4.667155, 4.667155
458000, 1, 4.853158, 4.853158, 4.853158, 4.853158
```

Contiguous (i.e. unchunked):
```
(python) kolossus  .../submodules/hal/chain/test  > ./blockVizBenchmark.py --reps 10 ~/progressiveCactus/mammals1/original_uncompressed_contiguous.hal simHuman_chr6 simHuman.chr6 500000 simCow_chr6 --seed 340340                                                                                                                                                                                       
Bin, nElem, totTime, minTime, maxTime, avgTime
2000, 1, 0.083569, 0.083569, 0.083569, 0.083569
10000, 1, 0.112364, 0.112364, 0.112364, 0.112364
93000, 1, 0.398447, 0.398447, 0.398447, 0.398447
165000, 1, 0.752554, 0.752554, 0.752554, 0.752554
231000, 1, 1.013472, 1.013472, 1.013472, 1.013472
384000, 1, 1.758252, 1.758252, 1.758252, 1.758252
411000, 1, 1.861496, 1.861496, 1.861496, 1.861496
422000, 1, 1.926926, 1.926926, 1.926926, 1.926926
442000, 1, 2.036885, 2.036885, 2.036885, 2.036885
458000, 1, 2.044122, 2.044122, 2.044122, 2.044122
```

**Comment by diekhans** [comment]
lets go with it.  Can you make a browser name version?

Mark

**Comment by joelarmstrong** [comment]
Will do. I'll try to put the repacking command into the pipeline as well, although I think we should probably just be generating the hals uncompressed in the first place.

BTW, is the HAL access for the mus-strain browser going through HTTP or directly through the local disk? I bet HTTP would add a ton of extra latency for each seek.

**Comment by diekhans** [comment]
Joel Armstrong <notifications@github.com> writes:
> BTW, is the HAL access for the mus-strain browser going through HTTP or
> directly through the local disk? I bet HTTP would add a ton of extra latency
> for each seek.

yes, it use direct file access.

**Comment by joelarmstrong** [comment]
OK, try using this:

/hive/groups/recon/projs/mus_strain_cactus/pipeline_data/comparative/1504/1504_browser_uncompressed_contiguous.hal

which is a bit bigger than the old one, at 102GB vs 38GB.

Not sure what kind of speedup it'll give exactly, but it seemed like quite a bit from the smaller test.

**Comment by diekhans** [comment]
The uncompressed hal does work at all.  Browser hangs until timeout..

**Comment by joelarmstrong** [comment]
Hmm, I'm getting sensible results through the same APIs that the browser ultimately uses--although haven't checked whether it's appreciably faster/slower. I'm not too familiar with the browser building process, but will try to debug tomorrow.
