### ISSUE TITLE
gene common name and ENS ID aren't indexed on non-ref genomes

### ISSUE THREAD

**Issue by joelarmstrong** [BD2KGenomics/mouseStrains#49]
E.g.: searching for Chd3 on A/J returns no results, but it works properly on C57B6J.

Basically the solution probably involves attaching the common name as an extra field to all the transmap and augustus tracks.

**Comment by ifiddes** [comment]
You can't search by ENS ID # on the assemblies either.

Ian Fiddes
PhD Candidate, Haussler lab
UC Santa Cruz Genomics Institute

**Comment by joelarmstrong** [comment]
OK, even more reason to fix the indices then. I can do this, I think--I have some experience with indexing on extra fields from the croc project.

**Comment by joelarmstrong** [comment]
OK, AUGUSTUS transcripts are now searchable by common name, transcript id, or munged id, and transmaps are searchable by transcript id or munged ID.
