### ISSUE TITLE
investigate why the long non-coding RNA genes are more poorly translated to NJ

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/mouseStrains#57]

**Comment by ifiddes** [comment]
A higher proportion of lincRNAs map over to strains at 100% coverage than protein coding transcripts do. This is more easily seen when looking at GencodeBasicVM4 for coding but GencodeCompVM4 for lincRNAs.

See http://hgwdev.cse.ucsc.edu/~ifiddes/lincRNA/GencodeCompVM4_coverage_coding.pdf
vs. 
http://hgwdev.cse.ucsc.edu/~ifiddes/lincRNA/GencodeCompVM4_coverage.pdf
