### ISSUE TITLE
determine why 300 transcripts mapped as okay by simplechain are not mapped as okay by transmap

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/mouseStrains#59]

**Comment by ifiddes** [comment]
Sent list of transcripts to Mark with classifier breakdown. Most common classsifier is alignmentPartialMap.

**Comment by diekhans** [comment]
The main cause I am seeing are small breaks in the chains.  These breaks mostly have sequence in a separate chain that seems like they should be part of main chain.  

In additions to gaps, this results in tiny mapped fragments of the gene.  I want to try to improve the chains.  However, a fall back is to filter the gene fragments and let AUGUSTUS fill in the gaps

**Comment by benedictpaten** [comment]
Are the small gaps due to alignment gaps, or are these recoverable from the
blocks passed to you?

**Comment by diekhans** [comment]
They appear to be the chainer not chaining in small blocks.

I need to dig more.  These are like 100-500bp blocks left out of
200mb chains, so its going to be a pain.

**Comment by diekhans** [comment]
here are three examples. I need to make a track of the unchained alignments ..

http://hgwdev.cse.ucsc.edu/~markd/mus_strain_cactus/genomic-chaining-examples/mus_strain_broken-chain-1.pdf
http://hgwdev.cse.ucsc.edu/~markd/mus_strain_cactus/genomic-chaining-examples/mus_strain_broken-chain-2.pdf
http://hgwdev.cse.ucsc.edu/~markd/mus_strain_cactus/genomic-chaining-examples/mus_strain_broken-chain-3.pdf

**Comment by benedictpaten** [comment]
Understood - you think it's a bug, or a feature of the
parameters/heuristics? :)

**Comment by diekhans** [comment]
Gathering data.

**Comment by diekhans** [comment]
here is an example that points the finger at hallLiftover.  Chaining works by creating a PSL of each chromosome using halLiftover --outPSL, and no other options.  The bottom track in this image  is the unchained blocks.  While the snake track shows an alignment running through this regions, the PSL substitutes the lower scoring paralogs (this is a pseudogene insertion),

Why is halLiftover not outputting all the blocks?  This also relates to why the syntinic filter didnt
do much good.

http://hgwdev.cse.ucsc.edu/~markd/mus_strain_cactus/genomic-chaining-examples/mus_strain_broken-chain-pseudo-1.pdf

**Comment by benedictpaten** [comment]
I see, hopefully the LOD within the snake code is not filling in the gap?
Joel can confirm.
