### ISSUE TITLE
refactor comparativeAnnotator to seamlessly integrate augustusTMR

### ISSUE THREAD

**Issue by ifiddes** [BD2KGenomics/mouseStrains#75]

**Comment by ifiddes** [comment]
Other goals:
1) Move away from the current paradigm so that I can restart individual classifiers without having to rerun everything. 
2) Load classifier results into one big pandas table before dumping to sql. This should be much, much faster.
3) Split out bedfile/bigbed creation into jobTree jobs.
4) Refactor into Toil?

**Comment by joelarmstrong** [comment]
I would suggest not converting to Toil just yet. There isn't that much benefit for comparativeAnnotator (unless you plan to run in AWS/Azure), and toil is still a bit unstable.

**Comment by ifiddes** [comment]
Alright, I will hold off on that part. I mostly just want to split apart
the Augustus from transMap and make the database loading method faster. It
should be easy to translate eventually.

Ian Fiddes
PhD Candidate, Haussler lab
UC Santa Cruz Genomics Institute
