### ISSUE TITLE
Redesign consensus to incorporate Pass/Good/Fail trinary concept

### ISSUE THREAD

**Issue by ifiddes** [BD2KGenomics/mouseStrains#79]

**Comment by ifiddes** [comment]
Below is a list of classifiers that a transcript must not fail to be in each category:

Pass: CodingInsertions (non multiple of 3), CodingDeletions (non multiple of 3), AlignmentPartialMap (100%), BadFrame, BeginStart, UnknownBases (refactored to be 1% of total bases), UnknownCdsBases (refactored to be 0.2% of CDS bases), CdsGap (non multiple of 3), CdsUnknownSplice (refactored to not count Ns), UtrUnknownSplice (refactored to not count Ns), EndStop, InFrameStop, ShortCds, StartOutOfFrame, FrameShift

Good:  CodingInsertions (non multiple of 3), CodingDeletions (non multiple of 3),  AlignmentPartialMap (95%), BadFrame, BeginStart, UnknownBases (refactored to be 5% of total bases), UnknownCdsBases (refactored to be 1% of CDS bases), CdsGap (non multiple of 3), CdsUnknownSplice (refactored to not count Ns), SpliceContainsNs, UtrUnknownSplice (refactored to not count Ns), EndStop, ShortCds, StartOutOfFrame, FrameShift

Fail: does not qualify for good or pass

Overview: Good relaxes the amount of Ns allowed and also allows Ns in splice sites. We no longer count having small UTR gaps against transcripts.

**Comment by joelarmstrong** [comment]
What's the interaction between AlignmentPartialMap and deletions? If there's a deletion, does that count as less than 100% map? Otherwise, looks good to me.

**Comment by ifiddes** [comment]
AlignmentPartialMap looks only at query coverage, aka is calculated as

a.qSize != a.qEnd - a.qStart

 From the PSL fields. So, from my understanding of how those fields are
filled out, a deletion will not count as less than 100% map unless the
deletion includes the terminal bases, which I think makes sense to consider
a partial mapping.

Ian Fiddes
PhD Candidate, Haussler lab
UC Santa Cruz Genomics Institute
