### ISSUE TITLE
Parameterize bar to be a little more greedy about aligning Ns, to match development

### ISSUE THREAD

**Issue by joelarmstrong** [BD2KGenomics/mouseStrains#9]

**Comment by benedictpaten** [comment]
If you set gapGamma=0.0 and matchGamma=0.2, you should basically match
development.

**Comment by joelarmstrong** [comment]
Closing this, I was thinking that it might help me find true coverage loss in the mice instead of coverage loss only involving Ns, but it was much easier to filter instead of rerunning.
